/**
 * Auto-generated translation types
 * DO NOT EDIT MANUALLY - Generated by scripts/i18n/generate-types.ts
 *
 * Run: npm run i18n:generate-types
 */

export interface CommonTranslations {
  buttons: {
    submit: string;
    cancel: string;
    save: string;
    delete: string;
    confirm: string;
    close: string;
    back: string;
    next: string;
    finish: string;
    start: string;
    pause: string;
    resume: string;
    reset: string;
    clear: string;
    apply: string;
    done: string;
    ok: string;
    yes: string;
    no: string;
  };
  messages: {
    loading: string;
    saving: string;
    success: string;
    error: string;
    saved: string;
    deleted: string;
    updated: string;
    noData: string;
    tryAgain: string;
    confirmDelete: string;
  };
  validation: {
    required: string;
    invalid: string;
    tooShort: string;
    tooLong: string;
    email: string;
    number: string;
  };
  time: {
    seconds: string;
    minutes: string;
    hours: string;
    days: string;
    second: string;
    minute: string;
    hour: string;
    day: string;
  };
  actions: {
    edit: string;
    view: string;
    download: string;
    upload: string;
    search: string;
    filter: string;
    sort: string;
    refresh: string;
    share: string;
    copy: string;
    paste: string;
    backToTop: string;
  };
}

export interface NavigationTranslations {
  menu: {
    home: string;
    kana: string;
    kanji: string;
    vocabulary: string;
    academy: string;
    achievements: string;
    statistics: string;
    progress: string;
    settings: string;
    preferences: string;
    about: string;
    help: string;
    logout: string;
  };
  breadcrumbs: {
    home: string;
    back: string;
  };
  footer: {
    copyright: string;
    privacy: string;
    terms: string;
    contact: string;
  };
}

export interface KanaTranslations {
  metadata: {
    title: string;
    description: string;
  };
  title: string;
  description: string;
  selection: {
    title: string;
    hiragana: string;
    katakana: string;
    selectAll: string;
    deselectAll: string;
    groups: {
      basic: string;
      dakuon: string;
      combo: string;
      yoon: string;
    };
  };
  game: {
    title: string;
    start: string;
    pause: string;
    resume: string;
    finish: string;
    nextQuestion: string;
    submit: string;
    score: string;
    timeLeft: string;
    streak: string;
    correct: string;
    incorrect: string;
    tryAgain: string;
  };
  modes: {
    pick: string;
    reversePick: string;
    input: string;
    reverseInput: string;
    description: {
      pick: string;
      reversePick: string;
      input: string;
      reverseInput: string;
    };
  };
  results: {
    title: string;
    congratulations: string;
    correct: string;
    incorrect: string;
    accuracy: string;
    timeSpent: string;
    playAgain: string;
    backToMenu: string;
  };
  dictionary: {
    title: string;
    search: string;
    character: string;
    romaji: string;
    type: string;
  };
}

export interface KanjiTranslations {
  title: string;
  description: string;
  selection: {
    title: string;
    byLevel: string;
    byCategory: string;
    selectAll: string;
    deselectAll: string;
    levels: {
      n5: string;
      n4: string;
      n3: string;
      n2: string;
      n1: string;
    };
  };
  game: {
    title: string;
    start: string;
    pause: string;
    resume: string;
    finish: string;
    nextQuestion: string;
    submit: string;
    score: string;
    timeLeft: string;
    streak: string;
    correct: string;
    incorrect: string;
    showAnswer: string;
    hint: string;
  };
  modes: {
    pick: string;
    reversePick: string;
    input: string;
    reverseInput: string;
    description: {
      pick: string;
      reversePick: string;
      input: string;
      reverseInput: string;
    };
  };
  results: {
    title: string;
    congratulations: string;
    correct: string;
    incorrect: string;
    accuracy: string;
    timeSpent: string;
    playAgain: string;
    backToMenu: string;
  };
  details: {
    meaning: string;
    readings: string;
    onyomi: string;
    kunyomi: string;
    examples: string;
    strokes: string;
    radical: string;
    jlptLevel: string;
  };
}

export interface VocabularyTranslations {
  title: string;
  description: string;
  selection: {
    title: string;
    byLevel: string;
    byCategory: string;
    selectAll: string;
    deselectAll: string;
    levels: {
      n5: string;
      n4: string;
      n3: string;
      n2: string;
      n1: string;
    };
    categories: {
      all: string;
      nouns: string;
      verbs: string;
      adjectives: string;
      adverbs: string;
      expressions: string;
    };
  };
  game: {
    title: string;
    start: string;
    pause: string;
    resume: string;
    finish: string;
    nextQuestion: string;
    submit: string;
    score: string;
    timeLeft: string;
    streak: string;
    correct: string;
    incorrect: string;
    showAnswer: string;
  };
  modes: {
    pick: string;
    reversePick: string;
    input: string;
    reverseInput: string;
    description: {
      pick: string;
      reversePick: string;
      input: string;
      reverseInput: string;
    };
  };
  results: {
    title: string;
    congratulations: string;
    correct: string;
    incorrect: string;
    accuracy: string;
    timeSpent: string;
    playAgain: string;
    backToMenu: string;
  };
  details: {
    word: string;
    reading: string;
    meaning: string;
    examples: string;
    type: string;
    jlptLevel: string;
  };
}

export interface AchievementsTranslations {
  title: string;
  description: string;
  unlocked: string;
  locked: string;
  progress: string;
  earnedOn: string;
  categories: {
    all: string;
    kana: string;
    kanji: string;
    vocabulary: string;
    general: string;
    special: string;
  };
  rarity: {
    common: string;
    rare: string;
    epic: string;
    legendary: string;
  };
  notifications: {
    achievementUnlocked: string;
    congratulations: string;
    youEarned: string;
  };
  stats: {
    totalAchievements: string;
    unlockedAchievements: string;
    completionRate: string;
    recentAchievements: string;
  };
}

export interface StatisticsTranslations {
  title: string;
  description: string;
  overview: {
    title: string;
    totalStudyTime: string;
    questionsAnswered: string;
    accuracy: string;
    currentStreak: string;
    longestStreak: string;
  };
  charts: {
    dailyActivity: string;
    accuracyOverTime: string;
    progressByLevel: string;
    timeByDojo: string;
  };
  kana: {
    title: string;
    mastered: string;
    learning: string;
    notStarted: string;
    hiraganaProgress: string;
    katakanaProgress: string;
  };
  kanji: {
    title: string;
    mastered: string;
    learning: string;
    notStarted: string;
    byLevel: string;
  };
  vocabulary: {
    title: string;
    wordsLearned: string;
    mastered: string;
    learning: string;
    byLevel: string;
  };
  performance: {
    title: string;
    bestAccuracy: string;
    fastestTime: string;
    longestSession: string;
    mostImproved: string;
  };
}

export interface SettingsTranslations {
  title: string;
  description: string;
  general: {
    title: string;
    language: string;
    theme: string;
    sound: string;
    notifications: string;
  };
  appearance: {
    title: string;
    colorTheme: string;
    font: string;
    fontSize: string;
    darkMode: string;
    customTheme: string;
  };
  game: {
    title: string;
    timeLimit: string;
    questionsPerSession: string;
    difficulty: string;
    autoNext: string;
    showHints: string;
  };
  audio: {
    title: string;
    soundEffects: string;
    volume: string;
    clickSound: string;
    correctSound: string;
    incorrectSound: string;
  };
  preferences: {
    title: string;
    showRomaji: string;
    showFurigana: string;
    inputMethod: string;
    keyboardShortcuts: string;
  };
  data: {
    title: string;
    exportData: string;
    importData: string;
    resetProgress: string;
    clearCache: string;
    confirmReset: string;
  };
  themes: {
    light: string;
    dark: string;
    system: string;
    custom: string;
    presets: string;
    createCustom: string;
  };
}

export interface ErrorsTranslations {
  general: {
    unknownError: string;
    networkError: string;
    serverError: string;
    notFound: string;
    unauthorized: string;
    forbidden: string;
    timeout: string;
  };
  validation: {
    required: string;
    invalidFormat: string;
    tooShort: string;
    tooLong: string;
    invalidEmail: string;
    invalidNumber: string;
    outOfRange: string;
  };
  game: {
    noSelection: string;
    loadFailed: string;
    saveFailed: string;
    invalidAnswer: string;
  };
  data: {
    loadFailed: string;
    saveFailed: string;
    exportFailed: string;
    importFailed: string;
    invalidData: string;
  };
}

export interface MenuInfoTranslations {
  greeting: string;
  description: string;
  instructions: string;
}

export interface BlogTranslations {
  pageTitle: string;
  pageDescription: string;
  metaTitle: string;
  metaDescription: string;
  categories: {
    all: string;
    hiragana: string;
    katakana: string;
    kanji: string;
    vocabulary: string;
    grammar: string;
    culture: string;
  };
  filter: {
    label: string;
    noResults: string;
  };
  card: {
    readMore: string;
  };
  post: {
    by: string;
    updated: string;
    readingTime: string;
    tableOfContents: string;
    relatedPosts: string;
  };
  difficulty: {
    beginner: string;
    intermediate: string;
    advanced: string;
  };
}

export interface TranslatorTranslations {
  meta: {
    title: string;
    description: string;
  };
  header: {
    title: string;
  };
  languages: {
    english: string;
    japanese: string;
    en: string;
    ja: string;
  };
  input: {
    placeholder: {
      en: string;
      ja: string;
    };
    clearButton: string;
    characterCount: string;
    keyboardHint: string;
    characterLimitWarning: string;
  };
  output: {
    placeholder: {
      en: string;
      ja: string;
    };
    copyButton: string;
    copied: string;
    copiedMessage: string;
    romanization: string;
  };
  actions: {
    translate: string;
    translating: string;
    swapLanguages: string;
  };
  history: {
    title: string;
    empty: string;
    emptyHint: string;
    clearAll: string;
    deleteEntry: string;
    clearDialog: {
      title: string;
      description: string;
      cancel: string;
      confirm: string;
    };
    timeAgo: {
      justNow: string;
      minutesAgo: string;
      hoursAgo: string;
      daysAgo: string;
    };
  };
  offline: {
    message: string;
  };
  errors: {
    networkError: string;
    rateLimit: string;
    invalidInput: string;
    emptyInput: string;
    serverError: string;
    authError: string;
    unknownError: string;
  };
  seo: {
    guideTitle: string;
    howToUse: {
      title: string;
      intro: string;
      steps: {
        step1: string;
        step2: string;
        step3: string;
        step4: string;
        step5: string;
      };
      proTip: string;
    };
    writingSystems: {
      title: string;
      intro: string;
      hiragana: {
        name: string;
        description: string;
      };
      katakana: {
        name: string;
        description: string;
      };
      kanji: {
        name: string;
        description: string;
      };
      outro: string;
    };
    faq: {
      title: string;
      isFree: {
        question: string;
        answer: string;
      };
      accuracy: {
        question: string;
        answer: string;
      };
      romanization: {
        question: string;
        answer: string;
      };
      historySaved: {
        question: string;
        answer: string;
      };
      maxLength: {
        question: string;
        answer: string;
      };
    };
  };
}

export interface MetadataTranslations {
  home: {
    title: string;
    titleShort: string;
    description: string;
    descriptionShort: string;
    keywords: string;
  };
  kana: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  learnHiragana: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  learnKatakana: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanaBlitz: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanaGauntlet: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanji: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanjiJlptN5: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanjiJlptN4: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanjiJlptN3: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanjiJlptN2: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanjiJlptN1: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanjiBlitz: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanjiGauntlet: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  vocabulary: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  vocabularyJlptN5: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  vocabularyJlptN4: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  vocabularyJlptN3: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  vocabularyJlptN2: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  vocabularyJlptN1: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  vocabularyBlitz: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  vocabularyGauntlet: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  academy: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  preferences: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  progress: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  privacy: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  terms: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  security: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  credits: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  patchNotes: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  faq: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  experiments: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  translate: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  zen: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanaTrain: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanjiTrain: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  vocabularyTrain: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanaSubset: {
    hiraganaBase: {
      title: string;
      titleShort: string;
      description: string;
      keywords: string;
    };
    hiraganaDakuon: {
      title: string;
      titleShort: string;
      description: string;
      keywords: string;
    };
    hiraganaYoon: {
      title: string;
      titleShort: string;
      description: string;
      keywords: string;
    };
    katakanaBase: {
      title: string;
      titleShort: string;
      description: string;
      keywords: string;
    };
    katakanaDakuon: {
      title: string;
      titleShort: string;
      description: string;
      keywords: string;
    };
    katakanaYoon: {
      title: string;
      titleShort: string;
      description: string;
      keywords: string;
    };
    katakanaForeign: {
      title: string;
      titleShort: string;
      description: string;
      keywords: string;
    };
  };
  hiraganaPractice: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  katakanaPractice: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
  kanjiPractice: {
    title: string;
    titleShort: string;
    description: string;
    keywords: string;
  };
}

export interface FaqTranslations {
  kicker: string;
  title: string;
  subtitle: string;
  links: {
    howToUse: string;
    glossary: string;
    translator: string;
    academy: string;
    privacy: string;
    terms: string;
  };
  nav: {
    title: string;
    backToTop: string;
    aria: string;
    note: string;
  };
  intro: {
    title: string;
    body: string;
  };
  cta: {
    hiragana: string;
    katakana: string;
    kanji: string;
  };
  footer: {
    title: string;
    body: string;
    links: {
      kana: string;
      progress: string;
    };
  };
  sections: {
    gettingStarted: {
      title: string;
      description: string;
      q1: {
        question: string;
        answer: string;
      };
      q2: {
        question: string;
        answer: string;
      };
      q3: {
        question: string;
        answer: string;
      };
    };
    learningPath: {
      title: string;
      description: string;
      q1: {
        question: string;
        answer: string;
      };
      q2: {
        question: string;
        answer: string;
      };
      q3: {
        question: string;
        answer: string;
      };
    };
    features: {
      title: string;
      description: string;
      q1: {
        question: string;
        answer: string;
      };
      q2: {
        question: string;
        answer: string;
      };
      q3: {
        question: string;
        answer: string;
      };
    };
    privacy: {
      title: string;
      description: string;
      q1: {
        question: string;
        answer: string;
      };
      q2: {
        question: string;
        answer: string;
      };
      q3: {
        question: string;
        answer: string;
      };
    };
    jlpt: {
      title: string;
      description: string;
      q1: {
        question: string;
        answer: string;
      };
      q2: {
        question: string;
        answer: string;
      };
      q3: {
        question: string;
        answer: string;
      };
    };
    troubleshooting: {
      title: string;
      description: string;
      q1: {
        question: string;
        answer: string;
      };
      q2: {
        question: string;
        answer: string;
      };
      q3: {
        question: string;
        answer: string;
      };
    };
  };
}

export interface PracticeLandingTranslations {
  hiragana: {
    title: string;
    subtitle: string;
    ctaPrimary: string;
    ctaSecondary: string;
    sections: {
      what: {
        title: string;
        body: string;
      };
      how: {
        title: string;
        bullets: string;
      };
      why: {
        title: string;
        bullets: string;
      };
    };
    links: {
      kana: string;
      train: string;
      blitz: string;
      gauntlet: string;
      faq: string;
    };
  };
  katakana: {
    title: string;
    subtitle: string;
    ctaPrimary: string;
    ctaSecondary: string;
    sections: {
      what: {
        title: string;
        body: string;
      };
      how: {
        title: string;
        bullets: string;
      };
      why: {
        title: string;
        bullets: string;
      };
    };
    links: {
      kana: string;
      train: string;
      blitz: string;
      gauntlet: string;
      faq: string;
    };
  };
  kanji: {
    title: string;
    subtitle: string;
    ctaPrimary: string;
    ctaSecondary: string;
    sections: {
      what: {
        title: string;
        body: string;
      };
      how: {
        title: string;
        bullets: string;
      };
      why: {
        title: string;
        bullets: string;
      };
    };
    links: {
      kanji: string;
      train: string;
      blitz: string;
      gauntlet: string;
      jlpt: string;
      faq: string;
    };
  };
}

export interface WelcomeTranslations {
  title: string;
  subtitle: string;
  steps: {
    welcome: {
      demoCta: string;
    };
    behavior: {
      title: string;
      subtitle: string;
      displayLanguage: {
        title: string;
        description: string;
        romaji: string;
        kana: string;
      };
      soundEffects: {
        title: string;
        description: string;
        on: string;
        off: string;
      };
    };
    themes: {
      title: string;
      subtitle: string;
      randomTheme: string;
      moreInfo: string;
      preferences: string;
    };
    fonts: {
      title: string;
      subtitle: string;
      randomFont: string;
      default: string;
      moreInfo: string;
      preferences: string;
    };
    complete: {
      title: string;
      subtitle: string;
      canChange: string;
      happyLearning: string;
    };
  };
  features: {
    behavior: {
      title: string;
      description: string;
    };
    theme: {
      title: string;
      description: string;
    };
    font: {
      title: string;
      description: string;
    };
  };
  navigation: {
    previous: string;
    back: string;
    next: string;
    getStarted: string;
    finishSetup: string;
  };
}

export interface ExperimentsTranslations {
  title: string;
  description: string;
  zenMode: {
    title: string;
    description: string;
  };
  breathing: {
    title: string;
    description: string;
  };
  ambient: {
    title: string;
    description: string;
  };
  constellation: {
    title: string;
    description: string;
  };
  rain: {
    title: string;
    description: string;
  };
  memory: {
    title: string;
    description: string;
  };
  sound: {
    title: string;
    description: string;
  };
  typing: {
    title: string;
    description: string;
  };
  haiku: {
    title: string;
    description: string;
  };
}

export interface LegalTranslations {
  privacy: {
    title: string;
    subtitle: string;
    lastUpdated: string;
  };
  terms: {
    title: string;
    subtitle: string;
    lastUpdated: string;
  };
  security: {
    title: string;
    subtitle: string;
    lastUpdated: string;
  };
  credits: {
    title: string;
    subtitle: string;
    contributors: {
      title: string;
      description: string;
    };
    sponsors: {
      title: string;
      description: string;
    };
    openSource: {
      title: string;
      description: string;
    };
  };
}

export interface KanaChartTranslations {
  title: string;
  subtitle: string;
  aboutTitle: string;
  aboutText: string;
  howToUseTitle: string;
  howToUse1: string;
  howToUse2: string;
  howToUse3: string;
  howToUse4: string;
  practiceTitle: string;
  practiceText: string;
}

export interface ConjugatorTranslations {
  meta: {
    title: string;
    titleWithVerb: string;
    description: string;
    descriptionWithVerb: string;
  };
  header: {
    title: string;
    subtitle: string;
  };
  input: {
    title: string;
    hint: string;
    placeholder: string;
    conjugateButton: string;
    conjugating: string;
    clearButton: string;
    keyboardHint: string;
  };
  results: {
    loading: string;
    empty: {
      title: string;
      hint: string;
    };
    statusMessage: string;
    expandAll: string;
    collapseAll: string;
    copyAll: string;
    copied: string;
    copiedMessage: string;
    formCount: string;
  };
  verbInfo: {
    type: string;
    stem: string;
    ending: string;
    compoundPrefix: string;
    conjugationRules: string;
  };
  verbTypes: {
    godan: {
      label: string;
      description: string;
      rules: string;
    };
    ichidan: {
      label: string;
      description: string;
      rules: string;
    };
    irregular: {
      label: string;
      description: string;
      rules: string;
    };
    suru: {
      label: string;
      description: string;
      rules: string;
    };
    kuru: {
      label: string;
      description: string;
      rules: string;
    };
    aru: {
      label: string;
      description: string;
      rules: string;
    };
    iku: {
      label: string;
      description: string;
      rules: string;
    };
    honorific: {
      label: string;
      description: string;
      rules: string;
    };
    unknown: {
      label: string;
      description: string;
      rules: string;
    };
  };
  categories: {
    basic: {
      name: string;
      nameJa: string;
    };
    polite: {
      name: string;
      nameJa: string;
    };
    negative: {
      name: string;
      nameJa: string;
    };
    past: {
      name: string;
      nameJa: string;
    };
    volitional: {
      name: string;
      nameJa: string;
    };
    potential: {
      name: string;
      nameJa: string;
    };
    passive: {
      name: string;
      nameJa: string;
    };
    causative: {
      name: string;
      nameJa: string;
    };
    'causative-passive': {
      name: string;
      nameJa: string;
    };
    imperative: {
      name: string;
      nameJa: string;
    };
    conditional: {
      name: string;
      nameJa: string;
    };
    'tai-form': {
      name: string;
      nameJa: string;
    };
    progressive: {
      name: string;
      nameJa: string;
    };
    honorific: {
      name: string;
      nameJa: string;
    };
  };
  forms: {
    polite: string;
    form: string;
    forms: string;
    reading: string;
    romaji: string;
    expand: string;
    collapse: string;
    copy: string;
    copyForm: string;
  };
  history: {
    title: string;
    empty: {
      title: string;
      hint: string;
    };
    verbCount: string;
    verbCountPlural: string;
    clearButton: string;
    clearDialog: {
      title: string;
      description: string;
      cancel: string;
      confirm: string;
    };
    removeEntry: string;
    timeAgo: {
      now: string;
      minutes: string;
      hours: string;
      days: string;
    };
  };
  share: {
    button: string;
    copied: string;
    error: string;
    title: string;
    text: string;
  };
  errors: {
    emptyInput: string;
    invalidCharacters: string;
    unknownVerb: string;
    ambiguousVerb: string;
    conjugationFailed: string;
  };
  accessibility: {
    mainRegion: string;
    inputRegion: string;
    resultsRegion: string;
    historyRegion: string;
    historySidebar: string;
    categoryToggle: string;
    categoryTogglePlural: string;
    categoryForms: string;
    verbInfoRegion: string;
    classificationDetails: string;
    rulesExplanation: string;
    showRules: string;
    hideRules: string;
    resultActions: string;
    keyboardShortcuts: string;
  };
  seo: {
    title: string;
    intro: string;
    verbIntro: string;
    verbTypesTitle: string;
    verbTypesGodan: {
      title: string;
      description: string;
    };
    verbTypesIchidan: {
      title: string;
      description: string;
    };
    verbTypesIrregular: {
      title: string;
      description: string;
    };
    commonFormsTitle: string;
    commonForms: {
      teForm: {
        name: string;
        description: string;
        example: string;
      };
      masuForm: {
        name: string;
        description: string;
        example: string;
      };
      potentialForm: {
        name: string;
        description: string;
        example: string;
      };
      passiveForm: {
        name: string;
        description: string;
        example: string;
      };
      causativeForm: {
        name: string;
        description: string;
        example: string;
      };
    };
    tipsTitle: string;
    tips: string;
    aboutTool: string;
  };
  faq: {
    title: string;
    expandAll: string;
    collapseAll: string;
    showMore: string;
    showLess: string;
    items: string;
  };
  relatedFeatures: {
    title: string;
    subtitle: string;
    links: {
      kana: {
        title: string;
        description: string;
      };
      kanji: {
        title: string;
        description: string;
      };
      vocabulary: {
        title: string;
        description: string;
      };
      translate: {
        title: string;
        description: string;
      };
      academy: {
        title: string;
        description: string;
      };
    };
    footer: string;
  };
}

export interface ResourcesTranslations {
  page: {
    title: string;
    subtitle: string;
    showingResults: string;
  };
  search: {
    placeholder: string;
    results: string;
    clearSearch: string;
    noResults: string;
    noResultsHint: string;
  };
  navigation: {
    allResources: string;
    categories: string;
    home: string;
    resources: string;
    viewAllCategories: string;
    relatedCategories: string;
    relatedCategoriesDescription: string;
    resourcesCount: string;
  };
  filters: {
    title: string;
    difficulty: string;
    price: string;
    platform: string;
    clearAll: string;
    activeFilters: string;
    removeFilter: string;
    expand: string;
    collapse: string;
  };
  difficulty: {
    beginner: string;
    intermediate: string;
    advanced: string;
    'all-levels': string;
  };
  priceType: {
    free: string;
    freemium: string;
    paid: string;
    subscription: string;
  };
  platform: {
    web: string;
    ios: string;
    android: string;
    windows: string;
    macos: string;
    linux: string;
    physical: string;
    'browser-extension': string;
    api: string;
  };
  card: {
    featured: string;
    availableOn: string;
    moreplatforms: string;
  };
  detail: {
    description: string;
    availableOn: string;
    tags: string;
    notes: string;
    visitResource: string;
    visitResourceLabel: string;
    relatedResources: string;
    rating: string;
  };
  categories: {
    apps: string;
    websites: string;
    textbooks: string;
    youtube: string;
    podcasts: string;
    games: string;
    jlpt: string;
    reading: string;
    listening: string;
    speaking: string;
    writing: string;
    grammar: string;
    vocabulary: string;
    kanji: string;
    immersion: string;
    community: string;
  };
  subcategories: {
    flashcards: string;
    dictionaries: string;
    comprehensive: string;
    'input-methods': string;
    courses: string;
    reference: string;
    practice: string;
    beginner: string;
    intermediate: string;
    advanced: string;
    specialized: string;
    lessons: string;
    culture: string;
    entertainment: string;
    'beginner-podcasts': string;
    'intermediate-podcasts': string;
    'native-content': string;
    rpg: string;
    'visual-novels': string;
    'educational-games': string;
    'casual-games': string;
    n5: string;
    n4: string;
    n3: string;
    n2: string;
    n1: string;
    'graded-readers': string;
    news: string;
    manga: string;
    novels: string;
    'audio-lessons': string;
    shadowing: string;
    comprehension: string;
    pronunciation: string;
    conversation: string;
    tutoring: string;
    handwriting: string;
    composition: string;
    correction: string;
    guides: string;
    'practice-grammar': string;
    'sentence-patterns': string;
    'frequency-lists': string;
    'themed-vocab': string;
    'word-lists': string;
    'learning-systems': string;
    'kanji-practice': string;
    'kanji-reference': string;
    'media-tools': string;
    streaming: string;
    'sentence-mining': string;
    forums: string;
    'language-exchange': string;
    discord: string;
  };
  accessibility: {
    resourceFilters: string;
    resourceList: string;
    loadingResources: string;
    categoryOptions: string;
    detailedDescription: string;
  };
  seo: {
    mainTitle: string;
    mainDescription: string;
    categoryTitle: string;
    categoryDescription: string;
  };
}

/**
 * Complete translation structure with all namespaces
 */
export interface Translations {
  common: CommonTranslations;
  navigation: NavigationTranslations;
  kana: KanaTranslations;
  kanji: KanjiTranslations;
  vocabulary: VocabularyTranslations;
  achievements: AchievementsTranslations;
  statistics: StatisticsTranslations;
  settings: SettingsTranslations;
  errors: ErrorsTranslations;
  menuInfo: MenuInfoTranslations;
  blog: BlogTranslations;
  translator: TranslatorTranslations;
  metadata: MetadataTranslations;
  faq: FaqTranslations;
  practiceLanding: PracticeLandingTranslations;
  welcome: WelcomeTranslations;
  experiments: ExperimentsTranslations;
  legal: LegalTranslations;
  kanaChart: KanaChartTranslations;
  conjugator: ConjugatorTranslations;
  resources: ResourcesTranslations;
}

/**
 * Type for translation keys with dot notation
 * Usage: const key: TranslationKey = 'common.buttons.submit';
 */
export type TranslationKey =
  | `common.${keyof CommonTranslations}`
  | `navigation.${keyof NavigationTranslations}`
  | `kana.${keyof KanaTranslations}`
  | `kanji.${keyof KanjiTranslations}`
  | `vocabulary.${keyof VocabularyTranslations}`
  | `achievements.${keyof AchievementsTranslations}`
  | `statistics.${keyof StatisticsTranslations}`
  | `settings.${keyof SettingsTranslations}`
  | `errors.${keyof ErrorsTranslations}`
  | `menuInfo.${keyof MenuInfoTranslations}`
  | `blog.${keyof BlogTranslations}`
  | `translator.${keyof TranslatorTranslations}`
  | `metadata.${keyof MetadataTranslations}`
  | `faq.${keyof FaqTranslations}`
  | `practiceLanding.${keyof PracticeLandingTranslations}`
  | `welcome.${keyof WelcomeTranslations}`
  | `experiments.${keyof ExperimentsTranslations}`
  | `legal.${keyof LegalTranslations}`
  | `kanaChart.${keyof KanaChartTranslations}`
  | `conjugator.${keyof ConjugatorTranslations}`
  | `resources.${keyof ResourcesTranslations}`;

/**
 * Available namespaces
 */
export type Namespace =
  | 'common'
  | 'navigation'
  | 'kana'
  | 'kanji'
  | 'vocabulary'
  | 'achievements'
  | 'statistics'
  | 'settings'
  | 'errors'
  | 'menuInfo'
  | 'blog'
  | 'translator'
  | 'metadata'
  | 'faq'
  | 'practiceLanding'
  | 'welcome'
  | 'experiments'
  | 'legal'
  | 'kanaChart'
  | 'conjugator'
  | 'resources';

/**
 * Available languages
 */
export type Locale =
  | 'en'
  | 'es'
  | 'pt'
  | 'fr'
  | 'de'
  | 'it'
  | 'zh'
  | 'ko'
  | 'ru'
  | 'ar';
